#!/usr/bin/env python3
"""Per-task wall-clock from run manifests versus the contract estimate.

python scripts/cost_table.py docs/acceptance --output docs/COST_TABLE.md
"""

from __future__ import annotations

import argparse
import json
import statistics
from collections import defaultdict
from datetime import datetime
from pathlib import Path


def seconds(a: str | None, b: str | None) -> float | None:
    if not a or not b:
        return None
    fa, fb = (datetime.fromisoformat(x.replace("Z", "+00:00")) for x in (a, b))
    return (fb - fa).total_seconds()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("root", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args(argv)
    per_skill: dict[str, list[float]] = defaultdict(list)
    estimates: dict[str, list[float]] = defaultdict(list)
    runs = []
    for path in sorted(args.root.rglob("run_manifest.json")):
        m = json.loads(path.read_text())
        if m.get("mode") != "real":
            continue
        est = {
            t["skill"]: float(t["seconds"])
            for t in (m.get("execution", {}).get("estimate", {}).get("per_task") or [])
        }
        total = seconds(m.get("started_at"), m.get("ended_at"))
        gpu_s = 0.0
        for task in m["tasks"].values():
            dt = seconds(task.get("started_at"), task.get("ended_at"))
            if dt is None or task.get("status") != "completed":
                continue
            per_skill[task["skill"]].append(dt)
            if task["skill"] in est:
                estimates[task["skill"]].append(est[task["skill"]])
            if task["skill"] in {
                "aframe.detect",
                "amplfi.pe",
                "gwak.scan",
                "deepclean.clean",
            }:
                gpu_s += dt
        runs.append(
            {
                "run": str(path.parent.relative_to(args.root)),
                "executor": m.get("execution", {}).get("executor"),
                "tasks": len(m["tasks"]),
                "wall_seconds": total,
                "gpu_task_seconds": gpu_s,
                "estimated_gpu_hours": m.get("execution", {})
                .get("estimate", {})
                .get("gpu_hours"),
            }
        )
    lines = [
        "# Cost table (generated by scripts/cost_table.py)",
        "",
        f"{len(runs)} real-mode runs under `{args.root}`.",
        "",
        "## Per-skill wall-clock (seconds)",
        "",
        "| skill | n | median | min | max | contract estimate (median) |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for skill, values in sorted(per_skill.items()):
        e = estimates.get(skill)
        lines.append(
            f"| `{skill}` | {len(values)} | {statistics.median(values):.1f} | "
            f"{min(values):.1f} | {max(values):.1f} | "
            f"{statistics.median(e):.1f} |"
            if e
            else f"| `{skill}` | {len(values)} | {statistics.median(values):.1f} | "
            f"{min(values):.1f} | {max(values):.1f} | — |"
        )
    lines += [
        "",
        "## Per-run totals",
        "",
        "| run | executor | tasks | wall s | GPU-task s | est. GPU h |",
        "|---|---|---:|---:|---:|---:|",
    ]
    for r in runs:
        w = f"{r['wall_seconds']:.0f}" if r["wall_seconds"] is not None else "—"
        e = f"{r['estimated_gpu_hours']:.4f}" if r["estimated_gpu_hours"] else "—"
        lines.append(
            f"| {r['run']} | {r['executor']} | {r['tasks']} | {w} | "
            f"{r['gpu_task_seconds']:.0f} | {e} |"
        )
    args.output.write_text("\n".join(lines) + "\n")
    print(f"{len(runs)} runs, {len(per_skill)} skills -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
