#!/usr/bin/env python3
"""Summarise a population run: one agent run per GWTC event.

    python scripts/population_compare.py <runs-root> \
        benchmarks/population/events.json --output summary.json --markdown POP.md

``<runs-root>/<event>/**/run_manifest.json`` (local or HTCondor copy-back
layout) is compared with the GWOSC catalog entry: Aframe recovery at the
calibrated threshold, coalescence-time offset, AMPLFI medians against the
catalog source-frame masses and distance, GWAK target score, rank and
measured background rate, plus task failures with their recorded reasons.
"""

from __future__ import annotations

import argparse
import json
import statistics
from pathlib import Path


def find_manifest(root: Path) -> Path | None:
    found = sorted(root.rglob("run_manifest.json"))
    workers = [p for p in found if "worker" in p.parts]
    return (workers or found or [None])[-1]


def summarise(event: str, catalog: dict, manifest: dict | None) -> dict:
    row: dict = {"event": event, "gps": catalog["gps"], "catalog": catalog}
    if manifest is None:
        row["status"] = "missing"
        return row
    tasks = manifest["tasks"]
    row["status"] = manifest.get("status")
    row["run_id"] = manifest.get("run_id")
    row["tasks"] = {k: t["status"] for k, t in tasks.items()}
    row["errors"] = {
        k: (t.get("error") or "")[:300] for k, t in tasks.items() if t.get("error")
    }
    a = (tasks.get("run_aframe") or {}).get("outputs") or {}
    if a:
        row["aframe"] = {
            "candidate_found": a.get("candidate_found"),
            "statistic": a.get("detection_statistic"),
            "threshold": a.get("threshold"),
            "threshold_calibrated": a.get("threshold_calibrated"),
            "tc_offset_seconds": a.get("target_offset_seconds"),
            "peak_in_window": a.get("peak_in_window"),
        }
    p = (tasks.get("run_amplfi") or {}).get("outputs") or {}
    ci = p.get("credible_intervals") or {}
    if ci:
        row["amplfi"] = {
            name: {k: ci[name].get(k) for k in ("median", "p5", "p95")}
            for name in (
                "chirp_mass_source",
                "mass_1_source",
                "mass_2_source",
                "distance",
                "chirp_mass",
            )
            if name in ci
        }
        row["amplfi"]["n_samples"] = p.get("n_samples")
        for key, cat_key in (
            ("chirp_mass_source", "chirp"),
            ("mass_1_source", "m1"),
            ("mass_2_source", "m2"),
            ("distance", "dL"),
        ):
            if key in row["amplfi"] and catalog.get(cat_key):
                med = row["amplfi"][key]["median"]
                row["amplfi"][key]["catalog"] = catalog[cat_key]
                row["amplfi"][key]["ratio"] = med / catalog[cat_key]
                lo, hi = row["amplfi"][key]["p5"], row["amplfi"][key]["p95"]
                row["amplfi"][key]["catalog_in_90"] = bool(lo <= catalog[cat_key] <= hi)
    g = (tasks.get("run_gwak") or {}).get("outputs") or {}
    if g:
        row["gwak"] = {
            k: g.get(k)
            for k in (
                "target_score",
                "target_zscore",
                "target_rank",
                "target_far_per_year",
                "max_score",
                "anomaly_found",
                "threshold",
            )
        }
    r = (tasks.get("reconcile_detections") or {}).get("outputs") or {}
    if r:
        row["reconcile"] = r.get("route") or r.get("verdict") or r
    return row


def markdown(rows: list[dict]) -> str:
    lines = [
        "# Population run summary (generated by scripts/population_compare.py)",
        "",
        "| event | run | SNR | m1/m2 (cat) | Aframe stat | found | tc off [s] "
        "| Mc src AMPLFI / cat | dL AMPLFI / cat | GWAK score (rank, FAR/yr) |",
        "|---|---|---:|---|---:|---|---:|---|---|---|",
    ]
    for r in rows:
        c = r["catalog"]
        a = r.get("aframe") or {}
        p = r.get("amplfi") or {}
        g = r.get("gwak") or {}
        mc = p.get("chirp_mass_source") or {}
        dl = p.get("distance") or {}
        fmt = lambda v, f="{:.2f}": f.format(v) if isinstance(v, (int, float)) else "—"  # noqa: E731
        lines.append(
            f"| {r['event']} | {r.get('status')} | {fmt(c.get('snr'), '{:.1f}')} | "
            f"{fmt(c.get('m1'), '{:.0f}')}/{fmt(c.get('m2'), '{:.0f}')} | "
            f"{fmt(a.get('statistic'))} | {a.get('candidate_found', '—')} | "
            f"{fmt(a.get('tc_offset_seconds'), '{:+.3f}')} | "
            f"{fmt(mc.get('median'), '{:.1f}')} / {fmt(mc.get('catalog'), '{:.1f}')} | "
            f"{fmt(dl.get('median'), '{:.0f}')} / {fmt(dl.get('catalog'), '{:.0f}')} | "
            f"{fmt(g.get('target_score'))} ({g.get('target_rank', '—')}, "
            f"{fmt(g.get('target_far_per_year'), '{:.0f}')}) |"
        )
    done = [r for r in rows if r.get("status") == "completed"]
    found = [r for r in done if (r.get("aframe") or {}).get("candidate_found")]
    in90 = [
        r["amplfi"]["chirp_mass_source"]["catalog_in_90"]
        for r in done
        if "chirp_mass_source" in (r.get("amplfi") or {})
        and "catalog_in_90" in r["amplfi"]["chirp_mass_source"]
    ]
    ratios = [
        r["amplfi"]["chirp_mass_source"]["ratio"]
        for r in done
        if "ratio" in (r.get("amplfi") or {}).get("chirp_mass_source", {})
    ]
    lines += [
        "",
        "## Totals",
        "",
        f"- events: {len(rows)}; runs completed: {len(done)}; "
        f"missing/failed: {len(rows) - len(done)}",
        f"- Aframe candidate at the calibrated threshold: {len(found)} of {len(done)}",
        (
            f"- AMPLFI source chirp mass: catalog inside the 90% interval for "
            f"{sum(in90)} of {len(in90)}; median ratio "
            f"{statistics.median(ratios):.3f}"
            if ratios
            else "- AMPLFI: no results"
        ),
    ]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("runs_root", type=Path)
    parser.add_argument("events", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--markdown", type=Path, default=None)
    args = parser.parse_args(argv)
    events = json.loads(args.events.read_text())
    rows = []
    for name, catalog in events.items():
        path = (
            find_manifest(args.runs_root / name)
            if (args.runs_root / name).is_dir()
            else None
        )
        manifest = json.loads(path.read_text()) if path else None
        rows.append(summarise(name, catalog, manifest))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(rows, indent=1) + "\n")
    if args.markdown:
        args.markdown.write_text(markdown(rows))
    completed = sum(r.get("status") == "completed" for r in rows)
    print(f"{len(rows)} events, {completed} completed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
